<?php /** @var $block \Montapacking\MontaCheckout\Block\Index */ ?>
<?php $logs = $block->getLogFiles(); ?>

<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title">
            <span class="title"<?= /* @noEscape */ __('Log Info') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-primary">
                <tr>
                    <th>Filename</th>
                    <th>Directory</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                    <th>Actions</th>
                </tr>
            <?php foreach ($logs as $log) {
                if ($log['name'] != "montapacking_checkout.log") {
                    continue;
                }
                ?>
                <tr>
                    <td><a href="<?=  /* @noEscape */ $block->previewLogFile($log['name']); ?>"><?=  /* @noEscape */ $log['name'] ?></a></td>
                    <td>var/log</td>
                    <td><?=  /* @noEscape */ $log['filesize'] ?></td>
                    <td><?=  /* @noEscape */ $log['modTimeLong'] ?></td>
                    <td>
                        <span class="action-children"><a href="<?=  /* @noEscape */ $block->previewLogFile($log['name']); ?>" class="icon-view"></a></span>
                        <span class="action-children"><a href="<?=  /* @noEscape */ $block->downloadLogFiles($log['name']); ?>" class="icon-export"></a></span>
                    </td>
                </tr>
            <?php } ?>
            </table>
        </div>
    </div>
</section>
<style>
    .icon-view:before {
        font-family: 'Admin Icons';
        content: '\e60c';
        color: #333333;
        -webkit-font-smoothing: antialiased;
        font-style: normal;
        font-weight: normal;
    }
    .icon-export:before {
        font-family: 'Admin Icons';
        content: '\e601';
        color: #333333;
        -webkit-font-smoothing: antialiased;
        font-style: normal;
        font-weight: normal;
    }
    .action-children {
        margin-right: 8px;
    }
    .action-children a:link {
        text-decoration:  none;
    }
</style>
