<?php /** @var $block \Montapacking\MontaCheckout\Block\View\Index */ ?>

<?php
    $count_lines = $block->countLines();
?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo $block->getFileName() ?></span>
            <a href="<?php echo $block->getBackUrl() ?>">Back</a>
            <a href="?clear">Clear log</a>

        </div>


        <div class="admin__page-section-item-content startfrom" style="padding-bottom: 10px; float: left">
            <span class="label"><?php echo __('Page no.:') ?></span>
            <?php
                $i = 0;
                $pagenumber = 0;
            ?>
            <?php
                $block_added = false;
            foreach ($block->getStarts() as $start) :
                if ($start >= $count_lines) {
                    break;
                }
                $pagenumber++;
                ?>
                <?php if ($start == $block->getStart()) : ?>
                    <span><strong><?php echo $pagenumber ?></strong></span>
                <?php else :
                    $block_added = true;
                    ?>
                    <a href="<?php echo $block->getStartUrl($start); ?>"><?php echo $pagenumber ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

        <div class="admin__page-section-item-content" style="padding-bottom: 10px; float: right;">
            <span class="label"><?php echo __('Items per page') ?></span>
            <?php foreach ($block->getLimits() as $limit) :
                if ($limit >= $count_lines) {
                    break;
                }
                ?>
                <?php if ($limit == $block->getLimit()) : ?>
                <span><strong><?php echo $limit ?></strong></span>
            <?php else : ?>
                <a href="<?php echo $block->getLimitUrl($limit); ?>"><?php echo $limit ?></a>
            <?php endif; ?>
            <?php endforeach; ?>
        </div>

        <div style="clear:both"></div>

        <?php if (false === $block_added) { ?>
        <style>
            .startfrom {
                display: none;
            }


        </style>
        <?php } ?>


        <div class="admin__page-section-item-content">
            <table style="width:100%; background:black;color:#2EC029; !important">
            <?php foreach ($block->getLogFileBlocks() as $time => $logBlock) : ?>
                <tr>
                    <td style="vertical-align: top; width: 200px; padding-left: 10px; padding-top:2px; padding-bottom: 2px; font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;">
                        <?php echo $time; ?>
                    </td>
                    <td style="vertical-align: top; font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;">

                            <?php

                            $value = strip_tags($logBlock);
                            $value = preg_replace('/{[\s\S]+?}/', '', $value);
                            $value = str_replace("[]", "", $value);
                            echo trim(str_replace("MontapackingLogger.NOTICE: ", "", $value));
                            ?>
                    </td>
                </tr>
            <?php endforeach; ?>
                <?php if (!count($block->getLogFileBlocks())) { ?>

                    <tr>
                        <td style="vertical-align: top; width: 200px; padding-left: 10px; padding-top:2px; padding-bottom: 2px; font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;">
                            <?php echo __('No logs available yet') ?>
                        </td>
                    </tr>

                <?php } ?>
            </table>
        </div>

        <div class="admin__page-section-item-content startfrom" style="padding-top: 10px;">
            <span class="label"><?php echo __('Page no.:') ?></span>
            <?php
            $i = 0;
            $pagenumber = 0;
            ?>
            <?php foreach ($block->getStarts() as $start) :
                if ($start >= $count_lines) {
                    break;
                }
                $pagenumber++;
                ?>
                <?php if ($start == $block->getStart()) : ?>
                    <span><strong><?php echo $pagenumber ?></strong></span>
                <?php else : ?>
                    <a href="<?php echo $block->getStartUrl($start); ?>"><?php echo $pagenumber ?></a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
</section>
